Repository Tamarind0/summer2021, pull requests merged in 2021-05, with the labels that each got.

#13 Added the Platform image to the art folder
  Project1/Assets/Art/Platform Pixel.png
  Project1/Assets/Art/Platform Pixel.png.meta
  Project1/Assets/Scenes/Main Menu.unity
Labels: Art

#21 Level design
  Project1/Assets/Prefab/PlatformWithCollider.prefab
  Project1/Assets/Scenes/GameOver.unity
  Project1/Assets/Scenes/GameOver.unity.meta
  Project1/Assets/Scenes/Main.unity
  Project1/Assets/Scripts/PlatformDespawner.cs
  Project1/Assets/Scripts/PlatformDespawner.cs.meta
  Project1/Assets/Scripts/PlatformGeneration.cs
  Project1/Assets/Scripts/PlayerDied.cs
  Project1/Assets/Scripts/PlayerDied.cs.meta
  Project1/Assets/Scripts/PlayerMovement.cs
  Project1/Assets/Scripts/ScoreDisplay.cs
  Project1/ProjectSettings/EditorBuildSettings.asset
  Project1/UserSettings/EditorUserSettings.asset
Labels: enhancement

#22 Color schemes
  Project1/Assets/Materials/Blue.asset
  Project1/Assets/Materials/Blue.asset.meta
  Project1/Assets/Materials/Inverse.asset
  Project1/Assets/Materials/Inverse.asset.meta
  Project1/Assets/Scenes/Change Outfit.unity
  Project1/Assets/Scenes/Change Outfit.unity.meta
  Project1/Assets/Scenes/GameOver.unity
  Project1/Assets/Scenes/Main Menu.unity
  Project1/Assets/Scenes/Main.unity
  Project1/Assets/Scripts/ButtonManager.cs
  Project1/Assets/Scripts/ButtonManager.cs.meta
  Project1/Assets/Scripts/LevelEnd.cs
  Project1/Assets/Scripts/LevelEnd.cs.meta
  Project1/Assets/Scripts/PlatformGeneration.cs
  Project1/Assets/Scripts/ScoreCounter.cs
  Project1/Assets/Scripts/ScoreCounter.cs.meta
  Project1/Assets/Scripts/ScoreDisplay.cs
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Outline.mat
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Project1/ProjectSettings/EditorBuildSettings.asset
  Project1/UserSettings/EditorUserSettings.asset
Labels: Art, UI

#32 Pause UI is done.
  Project1/Assets/Scenes/Main.unity
  Project1/Assets/Scripts/ButtonManager.cs
  Project1/Assets/Scripts/PauseMenu.cs
  Project1/Assets/Scripts/PauseMenu.cs.meta
  Project1/ProjectSettings/ProjectSettings.asset
Labels: UI, enhancement

#36 tweaked platform spawning
  Project1/Assets/AnimationController.cs
  Project1/Assets/AnimationController.cs.meta
  Project1/Assets/Animations/flip.anim
  Project1/Assets/Animations/flip.anim.meta
  Project1/Assets/Animations/playerAnimation.controller
  Project1/Assets/Animations/playerAnimation.controller.meta
  Project1/Assets/Animations/playerFlip.anim
  Project1/Assets/Animations/playerFlip.anim.meta
  Project1/Assets/Prefab/PlatformWithCollider.prefab
  Project1/Assets/Scenes/Main.unity
  Project1/Assets/Scripts/PlatformController.cs
  Project1/Assets/Scripts/PlatformGeneration.cs
Labels: enhancement

#39 Leaderboard aka High Score
  Project1/Assets/Scenes/Main.unity
  Project1/Assets/Scripts/ButtonManager.cs
  Project1/Assets/Scripts/LevelEnd.cs
  Project1/Assets/Scripts/PlayerSingleton.cs
  Project1/Assets/Scripts/ScoreCounter.cs
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/OdibeeSans-Regular SDF.asset
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/OdibeeSans-Regular SDF.asset.meta
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/OdibeeSans-Regular.ttf
  Project1/Assets/TextMesh Pro/Resources/Fonts & Materials/OdibeeSans-Regular.ttf.meta
  Project1/ProjectSettings/EditorBuildSettings.asset
  Project1/UserSettings/EditorUserSettings.asset
Labels: Art, UI, enhancement
